FROM registry.access.redhat.com/ubi9/python-312:latest

WORKDIR /opt/app-root
COPY requirements.txt .
RUN python3 -m pip install --upgrade pip setuptools wheel && \
    python3 -m pip install --no-cache-dir -r requirements.txt

COPY redbank-mcp/ redbank-mcp/

WORKDIR /opt/app-root/redbank-mcp

ENV PYTHONUNBUFFERED=1

EXPOSE 8000
CMD ["python3", "mcp_server.py"]
