apiVersion: v1
kind: Secret
metadata:
  name: inference-models-secret
  namespace: ragas-evaluation
type: Opaque
stringData:
  INFERENCE_MODEL: qwen3-14b-awq
  VLLM_URL: "http://qwen3-14b-awq-predictor:8080/v1"
  VLLM_API_TOKEN: fake
  VLLM_TLS_VERIFY: "false"
  INFERENCE_MODEL_2: RedHatAI/gpt-oss-20b
  VLLM_URL_2: http://redhataigpt-oss-20b-predictor:8080/v1
  VLLM_API_TOKEN_2: fake
  VLLM_TLS_VERIFY_2: "false"
