apiVersion: v1
kind: Secret
metadata:
  name: dashboard-dspa-secret
  labels:
    opendatahub.io/dashboard: "true"
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: minio
  AWS_SECRET_ACCESS_KEY: password
---
apiVersion: datasciencepipelinesapplications.opendatahub.io/v1
kind: DataSciencePipelinesApplication
metadata:
  name: dspa
spec:
  apiServer:
    artifactSignedURLExpirySeconds: 60
    caBundleFileMountPath: ""
    caBundleFileName: ""
    cacheEnabled: true
    deploy: true
    enableOauth: false
    enableSamplePipeline: false
    managedPipelines: {}
    pipelineStore: kubernetes
  database:
    disableHealthCheck: false
    mariaDB:
      deploy: true
      pipelineDBName: mlpipeline
      pvcSize: 10Gi
      username: mlpipeline
  dspVersion: v2
  objectStorage:
    disableHealthCheck: false
    enableExternalRoute: false
    externalStorage:
      basePath: ""
      bucket: ragas-evaluation-s3-bucket
      host: minio-service.ragas-evaluation.svc.cluster.local:9000
      port: ""
      region: us-east-1
      s3CredentialsSecret:
        accessKey: AWS_ACCESS_KEY_ID
        secretKey: AWS_SECRET_ACCESS_KEY
        secretName: dashboard-dspa-secret
      scheme: http
  persistenceAgent:
    deploy: true
    numWorkers: 2
  podToPodTLS: false
  scheduledWorkflow:
    cronScheduleTimezone: UTC
    deploy: true
