---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: playground
spec:
  lookupPolicy:
    local: false
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: python-312
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: 
    from:
      kind: DockerImage
      name: registry.redhat.io/ubi8/python-312
    generation: 1
    importPolicy:
      importMode: Legacy
    name: latest
    referencePolicy:
      type: Source
